stages:
  - build
  - migrate
  - deploy

variables:
  IMAGE_TAG: "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}"

build:
  stage: build
  tags:
    - prod-new
  script:
    - cat "$ENV_FILE" > .env
    - echo "Собираем Docker-образ $IMAGE_TAG..."
    - docker build -t $IMAGE_TAG .
  artifacts:
    paths:
      - .env
    expire_in: 1h

migrate:
  stage: migrate
  tags:
    - prod-new
  script:
    - cat "$ENV_FILE" > .env
    - echo "Запускаем миграции..."
    - docker run --rm --env-file .env $IMAGE_TAG npm run migrate

deploy:
  stage: deploy
  tags:
    - prod-new
  script:
    - cat "$ENV_FILE" > .env
    - echo "Останавливаем старый контейнер (если есть)..."
    - docker rm -f $CI_PROJECT_NAME || true
    - docker run -d --name $CI_PROJECT_NAME --env-file .env -p 3003:3003 $IMAGE_TAG
    - rm -f .env