/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as MembersRouteImport } from './routes/members'
import { Route as OrgRouteImport } from './routes/org'
import { Route as TaskflowRouteImport } from './routes/taskflow'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as BotsIndexRouteImport } from './routes/bots.index'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as BotsNewRouteImport } from './routes/bots.new'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskflowRoute = TaskflowRouteImport.update({
  id: '/taskflow',
  path: '/taskflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots/': typeof BotsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots': typeof BotsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots/': typeof BotsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/members'
    | '/org'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/tasks/$taskId'
    | '/bots/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/members'
    | '/org'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/tasks/$taskId'
    | '/bots'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/members'
    | '/org'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/tasks/$taskId'
    | '/bots/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  MembersRoute: typeof MembersRoute
  OrgRoute: typeof OrgRoute
  TaskflowRoute: typeof TaskflowRoute
  TeamRoute: typeof TeamRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsNewRoute: typeof BotsNewRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  BotsIndexRoute: typeof BotsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskflow': {
      id: '/taskflow'
      path: '/taskflow'
      fullPath: '/taskflow'
      preLoaderRoute: typeof TaskflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  MembersRoute: MembersRoute,
  OrgRoute: OrgRoute,
  TaskflowRoute: TaskflowRoute,
  TeamRoute: TeamRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  BotsNewRoute: BotsNewRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  BotsIndexRoute: BotsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
