/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as MembersRouteImport } from './routes/members'
import { Route as OrgRouteImport } from './routes/org'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as TaskflowRouteImport } from './routes/taskflow'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as BotsIndexRouteImport } from './routes/bots.index'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as BotsNewRouteImport } from './routes/bots.new'
import { Route as ChangeRequestsIndexRouteImport } from './routes/change-requests.index'
import { Route as ChangeRequestsNewRouteImport } from './routes/change-requests.new'
import { Route as IntegrationsProviderRouteImport } from './routes/integrations.$provider'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as IntegrationsProviderIntegrationIdRouteImport } from './routes/integrations.$provider.$integrationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskflowRoute = TaskflowRouteImport.update({
  id: '/taskflow',
  path: '/taskflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRequestsIndexRoute = ChangeRequestsIndexRouteImport.update({
  id: '/change-requests/',
  path: '/change-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRequestsNewRoute = ChangeRequestsNewRouteImport.update({
  id: '/change-requests/new',
  path: '/change-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsProviderRoute = IntegrationsProviderRouteImport.update({
  id: '/integrations/$provider',
  path: '/integrations/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsProviderIntegrationIdRoute =
  IntegrationsProviderIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => IntegrationsProviderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/departments': typeof DepartmentsRoute
  '/director': typeof DirectorRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/roles': typeof RolesRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/change-requests/new': typeof ChangeRequestsNewRoute
  '/integrations/$provider': typeof IntegrationsProviderRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots/': typeof BotsIndexRoute
  '/change-requests/': typeof ChangeRequestsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/integrations/$provider/$integrationId': typeof IntegrationsProviderIntegrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/departments': typeof DepartmentsRoute
  '/director': typeof DirectorRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/roles': typeof RolesRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/change-requests/new': typeof ChangeRequestsNewRoute
  '/integrations/$provider': typeof IntegrationsProviderRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots': typeof BotsIndexRoute
  '/change-requests': typeof ChangeRequestsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/integrations/$provider/$integrationId': typeof IntegrationsProviderIntegrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/departments': typeof DepartmentsRoute
  '/director': typeof DirectorRoute
  '/members': typeof MembersRoute
  '/org': typeof OrgRoute
  '/roles': typeof RolesRoute
  '/taskflow': typeof TaskflowRoute
  '/team': typeof TeamRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/change-requests/new': typeof ChangeRequestsNewRoute
  '/integrations/$provider': typeof IntegrationsProviderRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/bots/': typeof BotsIndexRoute
  '/change-requests/': typeof ChangeRequestsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/integrations/$provider/$integrationId': typeof IntegrationsProviderIntegrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/departments'
    | '/director'
    | '/members'
    | '/org'
    | '/roles'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/change-requests/new'
    | '/integrations/$provider'
    | '/tasks/$taskId'
    | '/bots/'
    | '/change-requests/'
    | '/tasks/'
    | '/integrations/$provider/$integrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/departments'
    | '/director'
    | '/members'
    | '/org'
    | '/roles'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/change-requests/new'
    | '/integrations/$provider'
    | '/tasks/$taskId'
    | '/bots'
    | '/change-requests'
    | '/tasks'
    | '/integrations/$provider/$integrationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/departments'
    | '/director'
    | '/members'
    | '/org'
    | '/roles'
    | '/taskflow'
    | '/team'
    | '/api/transcribe'
    | '/bots/$botId'
    | '/bots/new'
    | '/change-requests/new'
    | '/integrations/$provider'
    | '/tasks/$taskId'
    | '/bots/'
    | '/change-requests/'
    | '/tasks/'
    | '/integrations/$provider/$integrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DirectorRoute: typeof DirectorRoute
  MembersRoute: typeof MembersRoute
  OrgRoute: typeof OrgRoute
  RolesRoute: typeof RolesRoute
  TaskflowRoute: typeof TaskflowRoute
  TeamRoute: typeof TeamRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsNewRoute: typeof BotsNewRoute
  ChangeRequestsNewRoute: typeof ChangeRequestsNewRoute
  IntegrationsProviderRoute: typeof IntegrationsProviderRouteWithChildren
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  BotsIndexRoute: typeof BotsIndexRoute
  ChangeRequestsIndexRoute: typeof ChangeRequestsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskflow': {
      id: '/taskflow'
      path: '/taskflow'
      fullPath: '/taskflow'
      preLoaderRoute: typeof TaskflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-requests/': {
      id: '/change-requests/'
      path: '/change-requests'
      fullPath: '/change-requests/'
      preLoaderRoute: typeof ChangeRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-requests/new': {
      id: '/change-requests/new'
      path: '/change-requests/new'
      fullPath: '/change-requests/new'
      preLoaderRoute: typeof ChangeRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$provider': {
      id: '/integrations/$provider'
      path: '/integrations/$provider'
      fullPath: '/integrations/$provider'
      preLoaderRoute: typeof IntegrationsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$provider/$integrationId': {
      id: '/integrations/$provider/$integrationId'
      path: '/$integrationId'
      fullPath: '/integrations/$provider/$integrationId'
      preLoaderRoute: typeof IntegrationsProviderIntegrationIdRouteImport
      parentRoute: typeof IntegrationsProviderRoute
    }
  }
}

interface IntegrationsProviderRouteChildren {
  IntegrationsProviderIntegrationIdRoute: typeof IntegrationsProviderIntegrationIdRoute
}

const IntegrationsProviderRouteChildren: IntegrationsProviderRouteChildren = {
  IntegrationsProviderIntegrationIdRoute:
    IntegrationsProviderIntegrationIdRoute,
}

const IntegrationsProviderRouteWithChildren =
  IntegrationsProviderRoute._addFileChildren(IntegrationsProviderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  DepartmentsRoute: DepartmentsRoute,
  DirectorRoute: DirectorRoute,
  MembersRoute: MembersRoute,
  OrgRoute: OrgRoute,
  RolesRoute: RolesRoute,
  TaskflowRoute: TaskflowRoute,
  TeamRoute: TeamRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  BotsNewRoute: BotsNewRoute,
  ChangeRequestsNewRoute: ChangeRequestsNewRoute,
  IntegrationsProviderRoute: IntegrationsProviderRouteWithChildren,
  TasksTaskIdRoute: TasksTaskIdRoute,
  BotsIndexRoute: BotsIndexRoute,
  ChangeRequestsIndexRoute: ChangeRequestsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
